element:
  addGoods_page:
    # addType:
    commonAdd_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[1]/div/div/div[1]/label[1]/span[1]/input
    customAdd_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[1]/div/div/div[1]/label[2]/span[1]/input
    # goodsInfo:
    actuals_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[1]/div/div[1]/label[1]/span[1]/input
    futures_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[1]/div/div[1]/label[2]/span[1]/input
    shipName_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[2]/div/div[1]/input
    shipment_startTime_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[1]/div/div/span/span/input[1]
    shipment_endTime_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[1]/div/div/span/span/input[2]
    depart_time_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[2]/div/div/span/div/input
    arrival_time_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[3]/div/div/span/div/input
    pickup_time_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[4]/div/div/span/div/input
    futures_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/p
    ironOre_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/div[1]/label[1]/span[1]/input
    coal_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/div[1]/label[2]/span[1]/input
    coke_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/div[1]/label[3]/span[1]/input
    pigIron_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/div[1]/label[4]/span[1]/input
    billetSteel_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/div[1]/label[5]/span[1]/input
    normType_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[1]/div/div[1]/div/div
    material_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[1]/div/div/div[1]/input
    standard_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div/div[1]/input
    size_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[3]/div/div/div[1]/input
    place_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[1]/div/div/div[1]/div/div
    currency_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[2]/div/div/div[1]/div/div
    currency_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[2]/div/div/div[1]/ul/li[2]
    goodsName_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[3]/div/div/div[1]/input
    moreOrLess_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[4]/div/div/div[1]/input
    # endTime
    endTime_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[3]/div/div/span/div/input
    endTime_button_loc:
      xpath:
        html/body/div[3]/div/div/div/div/div[2]/div[3]/span/a
    # priceAndQuantity:
    goodsPrice_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div[1]/div/div[1]/input
    goodsPriceUnit_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div[2]/div/div[1]/div/div
    goodsPriceUnit_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div[2]/div/div[1]/ul/li[2]
    valuationType_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[2]/div/div/div[1]/div/div
    stock_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[3]/div/div/div[1]/input
    stockNum_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[3]/div/div/div[1]/div/span
    miniOrder_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[4]/div/div/div[1]/input
    miniOrderNum_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[4]/div/div/div[1]/div/span
    # otherInfo:
    payOnline_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[1]/div/div[1]/label[1]/span[1]/input
    payAccept_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[1]/div/div[1]/label[2]/span[1]/input
    payCreditCard_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[1]/div/div[1]/label[3]/span[1]/input
    payTransfer_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[1]/div/div[1]/label[4]/span[1]/input
    payAdvance_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[2]/div/div[1]/label[1]/span[1]/input
    payByInstalment_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[2]/div/div[1]/label[2]/span[1]/input
    payByStage_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[2]/div/div[1]/label[3]/span[1]/input
    port_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[3]/div/div[1]/label[1]/span[1]/input
    port_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div
    depot_radio_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[3]/div/div[1]/label[2]/span[1]/input
    depot_addAddress_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/button
    depot_addAddress_window_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div
    depot_addAddress_consignor_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[2]/div/div[1]/div/div[1]/input
    depot_addAddress_detail_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[2]/div/div[3]/div/div[1]/input
    depot_addAddress_companyName_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[2]/div/div[4]/div/div[1]/input
    depot_addAddress_depot_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[2]/div/div[5]/div/div[1]/input
    depot_addAddress_contact_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[2]/div/div[6]/div/div[1]/input
    depot_addAddress_confirm_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div[2]/div/div[3]/div/button[1]
    depot_addressList_first_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/div/label[1]/span[2]/span
    depot_showMore_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[4]/div/div/div[1]/div/button
    uploadPic_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[5]/div/div[1]/span/div[2]/span
    uploadPic_file_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[5]/div/div[1]/span/div[2]/span/input
    uploadPic_done_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[5]/div/div[1]/span/div[1]/div/div
    uploadPic_review_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[5]/div/div[1]/span/div[1]/div/span/a/i
    uploadPic_review_close_button_loc:
      xpath:
        html/body/div[2]/div/div/div[2]/div/div[1]/span
    uploadPic_delete_button_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[5]/div/div[1]/span/div[1]/div/span/i
    # submitButton
    submit_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div/button[1]
    draft_button_loc:
      xpath:
        .//*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div/button[2]
    goback_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div/button[3]
    # required info
    shipName_text_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[2]/div/div[2]/div
    goodsName_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[3]/div/div/div[2]/div
    goodsPrice_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div[1]/div/div[2]/div
    stock_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[3]/div/div/div[2]/div
    miniOrder_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[4]/div/div/div[2]/div
    payType_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[1]/div/div[2]/div
    payTime_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[5]/div[2]/div/div[2]/div
    # ironOre
    Fe_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[1]/div[2]/div/div/div[1]/input
    SiO2_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[2]/div[2]/div/div/div[1]/input
    AI2O3_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[3]/div[2]/div/div/div[1]/input
    S_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[4]/div[2]/div/div/div[1]/input
    P_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[5]/div[2]/div/div/div[1]/input
    H2O_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[6]/div[2]/div/div/div[1]/input
    FeO_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[7]/div[2]/div/div/div[1]/input
    Grade_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div/div[1]/div[8]/div[2]/div/div/div[1]/input