element:
  addressManger_page:
    postAdress_span_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/span[2]
    newGetAdress_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div/button
    getPerson_textBox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[1]/div/div[1]/input
    deatilAdress_textBox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[3]/div/div[1]/textarea
    companyName_textBox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[4]/div/div[1]/input
    contactInformation_textBox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[5]/div/div[1]/input
    postContactInformation_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[6]/div/div[1]/input
    horbor_textBox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[5]/div/div[1]/input
    keep_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[7]/button
    post_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div[8]/button
    data_table_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/table/tbody
    name_table_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/table/thead

