element:
  cart_page:
    goodsDetail_cartAccount_span_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div/div[1]/div[3]/a/span[2]
    goodsCart_cartAccount_span_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[1]/div[2]/div/div[1]/div[3]/a/span[2]
    goodsList_goodsName_text_loc:
      xpath:
        .//*[@id='root']/div/div[5]/div/table/tbody/tr[1]/td[2]/a
    goodsList_table_data_loc:
      xpath:
        .//*[@id='root']/div/div[5]/div/table/tbody
    goodsList_table_name_loc:
      xpath:
        .//*[@id='root']/div/div[5]/div/table/thead
    goodsDetail_addCart_button_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[2]/div/div[5]/button[2]
    addCart_info_skipToCart_button_loc:
      xpath:
        //div[2]/div/div[2]/div/button[1]
    addCart_info_keepShopping_button_loc:
      xpath:
        //div[2]/div/div[2]/div/button[2]
    cartGoods_name_text_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[2]/a/div[2]/p[2]
    enterShop_button_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[3]/div/div[5]/button[1]
    shopDetail_goodsList_table_data_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody
    shopDetail_goodsList_table_name_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/thead
    shopDetail_addCart_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody/tr/td[8]/div/button[1]
    shopDetail_addFavorite_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody/tr/td[8]/div/button[2]
    purchaseAccount_input_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[2]/div/div[4]/div/input
    goodsCart_purchaseAccount_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[7]/div/input
    goodsCart_unitPrice_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[6]
    goodsCart_total_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[8]/div
    myCart_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div/div[1]/div[3]/a
    deleteGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[9]/div/button[3]
    cart_addFavourite_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[9]/div/button[2]
    cart_shiftInFavourite_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div/div/table/tbody/tr/td[9]/div/button[1]
    cart_member_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[1]/div[1]/div/div[3]/a[2]