element:
  member_page:
    myGoods_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/a
    addGoods_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/a
    enterpriseInfo_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[3]/a
    myResource_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[4]/a
    addResource_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[5]/a
    info_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[6]/a
    favorite_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[7]/a
    addressManager_href_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[11]/a
    address_table_name_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/table/thead
    address_table_data_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/table/tbody