element:
  myFavorite_page:
    product_goodsName_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div/div[3]/div/table/tbody/tr[1]/td[2]/a
    addFavorite_button_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[1]/div[2]/span/span
    addFavorite_status_text_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[1]/div[2]/span
    myFavorite_goodsName_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/div/table/tbody/tr/td[2]/a/div[2]/p[2]
    addShop_button_loc:
      xpath:
        .//*[@id='root']/div/div[3]/div/div/div[3]/div/div[5]/button[2]
    favoriteShop_tab_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div/a[2]
    favoriteGoods_delete_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/div/table/tbody/tr/td[7]/div/button
    favoriteShop_delete_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/ul/li[1]/div[4]/button
    favoriteShop_enterShopDetail_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/ul/li[1]/div[4]/a
    shopDetail_goodsName_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody/tr/td[1]/a
    favoriteGoods_checkAll_checkbox_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/div/table/thead/tr/th[1]/div/div/label/input
    addToCart_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/span/div/div/div/div/button[2]