element:
  myGoods_page:
    addGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[3]/div/button
    allGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/button[1]
    saleGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/button[2]
    draftGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/button[3]
    pauseGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/button[4]
    soldOutGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/button[5]
    myGoods_table_name_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/thead
    myGoods_table_data_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody
    goods_button1_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody/tr[1]/td[9]/div/button[1]
    goods_button2_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody/tr[1]/td[9]/div/button[2]
    goods_button3_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody/tr[1]/td[9]/div/button[3]
    goods_button4_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody/tr[1]/td[9]/div/button[4]
    goods_button5_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[3]/table/tbody/tr[1]/td[9]/div/button[5]
    goodsInfo_goodsName_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div[5]/div[3]/div/div/div[1]/input
    goodsInfo_sale_button_loc:
      xpath:
        .//*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div/button[1]
    goodsInfo_draft_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div/button[2]
    confirm_button_loc:
      xpath:
        //div[3]/span/button
    batchSale_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/button[1]
    batchDelete_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[2]/button[2]
    addTime_select_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[1]/select
    selectGoods_input_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/input
    selectGoods_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/button
    resultText_text_loc:
      xpath:
        //*[@id="root"]/div/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[2]/span