element:
  storeDetail_page:
    store_img_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[1]/div[1]/img
    shopName_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[1]/p[1]
    majorGoods_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div[1]/ul/li/span
    majorType_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[2]/div[2]/ul/li
    mainHarhour_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div/ul/li[1]/a
    contacts_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div/ul/li[2]/a
    contactsInformation_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div/ul/li[3]/a
    qqNumber_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[2]/div[1]/div/ul/li[4]/a
    shopPro_text_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[2]/div[1]/p[2]
    table_data_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody
    table_name_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/thead
    firstLineCar_button_loc:
      xpath:
        .//*[@id="root"]/div/div[1]/div[3]/div[2]/table/tbody/tr/td[8]/div/button[1]
    firstLineCollection_button_loc:
      xpath:
        .//*[@id='root']/div/div[1]/div[3]/div[2]/table/tbody/tr/td[8]/div/button[2]
    alertWords_text_loc:
      xpath:
        ./html/body/div[2]/div/div/div[2]/div/div[2]/div/p
    alertGoToSee_button_loc:
      xpath:
        ./html/body/div[2]/div/div/div[2]/div/div[2]/div/button[1]

